name = "banana"
main = "src/worker.ts"
compatibility_date = "2024-04-05"

[assets]
directory = "dist"

[[kv_namespaces]]
binding = "CREDITS_KV"
id = "5a4fb269ece1409b8ec1da3fbdf6e983"
preview_id = "5a4fb269ece1409b8ec1da3fbdf6e983"
